
# File: .github/workflows/repo-sync.yml
name: sync-shylocks-Loon
on:
  schedule:
    - cron: '5 0,7,15 * * *'
  workflow_dispatch:
  watch:
    types: started
  push:
    branches: [ main ]
  repository_dispatch:
    types: sync-shylocks-Loon
jobs:
  pull-request:
    env:
      PAT: ${{ secrets.PAT }} #此处PAT需要申请，教程详见：https://www.jianshu.com/p/bb82b3ad1d11
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: pull-request
        uses: repo-sync/pull-request@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/shylocks/Loon.git"
          source_branch: "main"
          destination_branch: "main"
          github_token: ${{ secrets.PAT }}
